public class OiMundo{
     public static void main(String[] args) {
        //A linha abaixo envia uma mensagem para o monitor

        /*Esse comentario
         * entao tudo sera ignorado
         * dentro do codigo
        */


        System.out.println("Oi \"Mundo\"");        
        System.out.println("Oi \\Mundo\\");
        System.out.println("Oi \nMundo");
        
        /*
         *  Oi "Mundo"
            \Mundo\
            Oi 
            Mundo
         */
        

    }

}