/*PALAVRAS RESERVADAS
 * public
 * return
 * short
 * static
 * strictfp
 * throws
 * assert
 * enum
 * super
 * switch
 * synchronized
 * void
 * try
 * transient
 * this
 * volatile
 * throw
 * while
 * 
 * public class OiMundo {

Isso declara a classe chamada OiMundo. O nome da classe deve ser o mesmo que o nome do arquivo Java que a contém. Neste caso, o arquivo Java deve ser chamado OiMundo.java. A palavra-chave public indica que a classe é acessível de outros lugares do programa.
public static void main(String[] args) {

Este é o método main, que é o ponto de entrada para a execução do programa Java. É onde o programa começa a ser executado. O método main é obrigatório em qualquer programa Java e possui a seguinte estrutura básica:
public: A palavra-chave public indica que o método é acessível de outros lugares do programa.
static: A palavra-chave static indica que o método pertence à classe em si, não a uma instância específica da classe.
void: O tipo de retorno do método main é void, o que significa que o método não retorna nenhum valor.
main: O nome do método é main.
String[] args: O parâmetro do método main é um array de strings chamado args. Ele permite que você passe argumentos para o programa quando ele é executado a partir da linha de comando.
Essa estrutura básica é comum em programas Java, e você pode adicionar o código específico do seu programa dentro do método main para executar as ações desejadas.
 */